/**
 * Type of item that can be added to the property pane
 */
export declare enum PropertyItemType {
    BlockList = 'editorUI:BlockList',
    BlockTable = 'editorUI:BlockTable',
    Boolean = 'editorUI:Boolean',
    Button = 'editorUI:Button',
    ButtonPane = 'editorUI:ButtonPane',
    CollectionTree = 'editorUI:CollectionTree',
    ColorPicker = 'editorUI:ColorPicker',
    ColorTimeline = 'editorUI:ColorTimeline',
    ComboBox = 'editorUI:ComboBox',
    DataTable = 'editorUI:DataTable',
    Divider = 'editorUI:Divider',
    Dropdown = 'editorUI:Dropdown',
    Image = 'editorUI:Image',
    Link = 'editorUI:Link',
    ListPane = 'editorUI:ListPane',
    Menu = 'editorUI:Menu',
    Minimap = 'editorUI:Minimap',
    Number = 'editorUI:Number',
    NumberTimeline = 'editorUI:NumberTimeline',
    ProgressIndicator = 'editorUI:ProgressIndicator',
    ProxyPane = 'editorUI:ProxyPane',
    String = 'editorUI:String',
    SubPane = 'editorUI:SubPane',
    Text = 'editorUI:Text',
    ToggleGroup = 'editorUI:ToggleGroup',
    Vector2 = 'editorUI:Vector2',
    Vector3 = 'editorUI:Vector3',
    Vector3Timeline = 'editorUI:Vector3Timeline',
}
