export enum PersonaPieceType {
    Arms = 'Arms',
    Back = 'Back',
    Body = 'Body',
    Bottom = 'Bottom',
    Capes = 'Capes',
    Dress = 'Dress',
    Eyes = 'Eyes',
    FaceAccessory = 'FaceAccessory',
    FacialHair = 'FacialHair',
    Feet = 'Feet',
    Hair = 'Hair',
    Hands = 'Hands',
    Head = 'Head',
    HighPants = 'HighPants',
    Hood = 'Hood',
    LeftArm = 'LeftArm',
    LeftLeg = 'LeftLeg',
    Legs = 'Legs',
    Mouth = 'Mouth',
    Outerwear = 'Outerwear',
    RightArm = 'RightArm',
    RightLeg = 'RightLeg',
    Skeleton = 'Skeleton',
    Skin = 'Skin',
    Top = 'Top',
}
