/* IMPORT */ import { BlockDynamicPropertiesComponent, BlockEntityStorageComponent, BlockFluidContainerComponent, BlockInstrumentComponent, BlockInventoryComponent, BlockMapColorComponent, BlockMovableComponent, BlockPistonComponent, BlockPrecipitationInteractionsComponent, BlockRecipeCraftingComponent, BlockRecipeProcessingComponent, BlockRecordPlayerComponent, BlockRedstoneProducerComponent, BlockSignComponent, BlockVibrationPropertiesComponent } from '..';

export type BlockComponentTypeMap = {
    dynamic_properties: BlockDynamicPropertiesComponent;
    entity_storage: BlockEntityStorageComponent;
    fluid_container: BlockFluidContainerComponent;
    instrument_sound: BlockInstrumentComponent;
    inventory: BlockInventoryComponent;
    map_color: BlockMapColorComponent;
    'minecraft:dynamic_properties': BlockDynamicPropertiesComponent;
    'minecraft:entity_storage': BlockEntityStorageComponent;
    'minecraft:fluid_container': BlockFluidContainerComponent;
    'minecraft:instrument_sound': BlockInstrumentComponent;
    'minecraft:inventory': BlockInventoryComponent;
    'minecraft:map_color': BlockMapColorComponent;
    'minecraft:movable': BlockMovableComponent;
    'minecraft:piston': BlockPistonComponent;
    'minecraft:precipitation_interactions': BlockPrecipitationInteractionsComponent;
    'minecraft:recipe_crafting': BlockRecipeCraftingComponent;
    'minecraft:recipe_processing': BlockRecipeProcessingComponent;
    'minecraft:record_player': BlockRecordPlayerComponent;
    'minecraft:redstone_producer': BlockRedstoneProducerComponent;
    'minecraft:sign': BlockSignComponent;
    'minecraft:vibration_properties': BlockVibrationPropertiesComponent;
    movable: BlockMovableComponent;
    piston: BlockPistonComponent;
    precipitation_interactions: BlockPrecipitationInteractionsComponent;
    recipe_crafting: BlockRecipeCraftingComponent;
    recipe_processing: BlockRecipeProcessingComponent;
    record_player: BlockRecordPlayerComponent;
    redstone_producer: BlockRedstoneProducerComponent;
    sign: BlockSignComponent;
    vibration_properties: BlockVibrationPropertiesComponent;
};
