/**
 * @beta
 */
export enum GameRule {
    CommandBlockOutput = 'commandBlockOutput',
    CommandBlocksEnabled = 'commandBlocksEnabled',
    DoDayLightCycle = 'doDayLightCycle',
    DoEntityDrops = 'doEntityDrops',
    DoFireTick = 'doFireTick',
    DoImmediateRespawn = 'doImmediateRespawn',
    DoInsomnia = 'doInsomnia',
    DoLimitedCrafting = 'doLimitedCrafting',
    DoMobLoot = 'doMobLoot',
    DoMobSpawning = 'doMobSpawning',
    DoTileDrops = 'doTileDrops',
    DoWeatherCycle = 'doWeatherCycle',
    DrowningDamage = 'drowningDamage',
    FallDamage = 'fallDamage',
    FireDamage = 'fireDamage',
    FreezeDamage = 'freezeDamage',
    FunctionCommandLimit = 'functionCommandLimit',
    KeepInventory = 'keepInventory',
    MaxCommandChainLength = 'maxCommandChainLength',
    MobGriefing = 'mobGriefing',
    NaturalRegeneration = 'naturalRegeneration',
    PlayersSleepingPercentage = 'playersSleepingPercentage',
    ProjectilesCanBreakBlocks = 'projectilesCanBreakBlocks',
    Pvp = 'pvp',
    RandomTickSpeed = 'randomTickSpeed',
    RecipesUnlock = 'recipesUnlock',
    RespawnBlocksExplode = 'respawnBlocksExplode',
    SendCommandFeedback = 'sendCommandFeedback',
    ShowBorderEffect = 'showBorderEffect',
    ShowCoordinates = 'showCoordinates',
    ShowDeathMessages = 'showDeathMessages',
    ShowRecipeMessages = 'showRecipeMessages',
    ShowTags = 'showTags',
    SpawnRadius = 'spawnRadius',
    TntExplodes = 'tntExplodes',
}