/**
 * All possible MinecraftEntityTypes
 */
export declare enum MinecraftEntityTypes {
    /** 智能体。 */
    Agent = "minecraft:agent",
    /** 悦灵。 */
    Allay = "minecraft:allay",
    /** 区域效果云。 */
    AreaEffectCloud = "minecraft:area_effect_cloud",
    /** 犰狳。 */
    Armadillo = "minecraft:armadillo",
    /** 盔甲架。 */
    ArmorStand = "minecraft:armor_stand",
    /** 箭。 */
    Arrow = "minecraft:arrow",
    /** 美西螈。 */
    Axolotl = "minecraft:axolotl",
    /** 蝙蝠。 */
    Bat = "minecraft:bat",
    /** 蜜蜂。 */
    Bee = "minecraft:bee",
    /** 烈焰人。 */
    Blaze = "minecraft:blaze",
    /** 船。 */
    Boat = "minecraft:boat",
    /** 沼骸。 */
    Bogged = "minecraft:bogged",
    /** 旋风人。 */
    Breeze = "minecraft:breeze",
    /** 风弹。 */
    BreezeWindChargeProjectile = "minecraft:breeze_wind_charge_projectile",
    /** 骆驼。 */
    Camel = "minecraft:camel",
    /** 猫。 */
    Cat = "minecraft:cat",
    /** 洞穴蜘蛛。 */
    CaveSpider = "minecraft:cave_spider",
    /** 运输船。 */
    ChestBoat = "minecraft:chest_boat",
    /** 运输矿车。 */
    ChestMinecart = "minecraft:chest_minecart",
    /** 鸡。 */
    Chicken = "minecraft:chicken",
    /** 鳕鱼。 */
    Cod = "minecraft:cod",
    /** 命令方块矿车。 */
    CommandBlockMinecart = "minecraft:command_block_minecart",
    /** 铜傀儡。 */
    CopperGolem = "minecraft:copper_golem",
    /** 牛。 */
    Cow = "minecraft:cow",
    /** 嘎枝。 */
    Creaking = "minecraft:creaking",
    /** 苦力怕。 */
    Creeper = "minecraft:creeper",
    /** 海豚。 */
    Dolphin = "minecraft:dolphin",
    /** 驴。 */
    Donkey = "minecraft:donkey",
    /** 末影龙火球。 */
    DragonFireball = "minecraft:dragon_fireball",
    /** 溺尸。 */
    Drowned = "minecraft:drowned",
    /** 鸡蛋。 */
    Egg = "minecraft:egg",
    /** 远古守卫者。 */
    ElderGuardian = "minecraft:elder_guardian",
    /** 末地水晶。 */
    EnderCrystal = "minecraft:ender_crystal",
    /** 末影龙。 */
    EnderDragon = "minecraft:ender_dragon",
    /** 末影珍珠。 */
    EnderPearl = "minecraft:ender_pearl",
    /** 末影人。 */
    Enderman = "minecraft:enderman",
    /** 末影螨。 */
    Endermite = "minecraft:endermite",
    /** 唤魔者。 */
    EvocationIllager = "minecraft:evocation_illager",
    /** 末影之眼。 */
    EyeOfEnderSignal = "minecraft:eye_of_ender_signal",
    /** 火球。 */
    Fireball = "minecraft:fireball",
    /** 烟花火箭。 */
    FireworksRocket = "minecraft:fireworks_rocket",
    /** 浮漂。 */
    FishingHook = "minecraft:fishing_hook",
    /** 狐狸。 */
    Fox = "minecraft:fox",
    /** 青蛙。 */
    Frog = "minecraft:frog",
    /** 恶魂。 */
    Ghast = "minecraft:ghast",
    /** 发光鱿鱼。 */
    GlowSquid = "minecraft:glow_squid",
    /** 山羊。 */
    Goat = "minecraft:goat",
    /** 守卫者。 */
    Guardian = "minecraft:guardian",
    /** 快乐恶魂。 */
    HappyGhast = "minecraft:happy_ghast",
    /** 疣猪兽。 */
    Hoglin = "minecraft:hoglin",
    /** 漏斗矿车。 */
    HopperMinecart = "minecraft:hopper_minecart",
    /** 马。 */
    Horse = "minecraft:horse",
    /** 尸壳。 */
    Husk = "minecraft:husk",
    /** 铁傀儡。 */
    IronGolem = "minecraft:iron_golem",
    /** 闪电束。 */
    LightningBolt = "minecraft:lightning_bolt",
    /** 滞留药水。 */
    LingeringPotion = "minecraft:lingering_potion",
    /** 羊驼。 */
    Llama = "minecraft:llama",
    /** 羊驼唾沫。 */
    LlamaSpit = "minecraft:llama_spit",
    /** 岩浆怪。 */
    MagmaCube = "minecraft:magma_cube",
    /** 矿车。 */
    Minecart = "minecraft:minecart",
    /** 哞菇。 */
    Mooshroom = "minecraft:mooshroom",
    /** 骡。 */
    Mule = "minecraft:mule",
    /** 鹦鹉螺。 */
    Nautilus = "minecraft:nautilus",
    /** NPC。 */
    Npc = "minecraft:npc",
    /** 豹猫。 */
    Ocelot = "minecraft:ocelot",
    /** 不祥之物生成器。 */
    OminousItemSpawner = "minecraft:ominous_item_spawner",
    /** 熊猫。 */
    Panda = "minecraft:panda",
    /** 鹦鹉。 */
    Parrot = "minecraft:parrot",
    /** 幻翼。 */
    Phantom = "minecraft:phantom",
    /** 猪。 */
    Pig = "minecraft:pig",
    /** 猪灵。 */
    Piglin = "minecraft:piglin",
    /** 猪灵蛮兵。 */
    PiglinBrute = "minecraft:piglin_brute",
    /** 掠夺者。 */
    Pillager = "minecraft:pillager",
    /** 玩家。 */
    Player = "minecraft:player",
    /** 北极熊。 */
    PolarBear = "minecraft:polar_bear",
    /** 河豚。 */
    Pufferfish = "minecraft:pufferfish",
    /** 兔子。 */
    Rabbit = "minecraft:rabbit",
    /** 劫掠兽。 */
    Ravager = "minecraft:ravager",
    /** 鲑鱼。 */
    Salmon = "minecraft:salmon",
    /** 绵羊。 */
    Sheep = "minecraft:sheep",
    /** 潜影贝。 */
    Shulker = "minecraft:shulker",
    /** 潜影弹。 */
    ShulkerBullet = "minecraft:shulker_bullet",
    /** 蠹虫。 */
    Silverfish = "minecraft:silverfish",
    /** 骷髅。 */
    Skeleton = "minecraft:skeleton",
    /** 骷髅马。 */
    SkeletonHorse = "minecraft:skeleton_horse",
    /** 史莱姆。 */
    Slime = "minecraft:slime",
    /** 小火球。 */
    SmallFireball = "minecraft:small_fireball",
    /** 嗅探兽。 */
    Sniffer = "minecraft:sniffer",
    /** 雪傀儡。 */
    SnowGolem = "minecraft:snow_golem",
    /** 雪球。 */
    Snowball = "minecraft:snowball",
    /** 蜘蛛。 */
    Spider = "minecraft:spider",
    /** 喷溅药水。 */
    SplashPotion = "minecraft:splash_potion",
    /** 鱿鱼。 */
    Squid = "minecraft:squid",
    /** 流浪者。 */
    Stray = "minecraft:stray",
    /** 炽足兽。 */
    Strider = "minecraft:strider",
    /** 蝌蚪。 */
    Tadpole = "minecraft:tadpole",
    /** 三叉戟。 */
    ThrownTrident = "minecraft:thrown_trident",
    /** 被激活的TNT。 */
    Tnt = "minecraft:tnt",
    /** TNT矿车。 */
    TntMinecart = "minecraft:tnt_minecart",
    /** 行商羊驼。 */
    TraderLlama = "minecraft:trader_llama",
    /** 摄像机。 */
    TripodCamera = "minecraft:tripod_camera",
    /** 热带鱼。 */
    Tropicalfish = "minecraft:tropicalfish",
    /** 海龟。 */
    Turtle = "minecraft:turtle",
    /** 恼鬼。 */
    Vex = "minecraft:vex",
    /** 村民。 */
    Villager = "minecraft:villager",
    /** 村民。 */
    VillagerV2 = "minecraft:villager_v2",
    /** 卫道士。 */
    Vindicator = "minecraft:vindicator",
    /** 流浪商人。 */
    WanderingTrader = "minecraft:wandering_trader",
    /** 监守者。 */
    Warden = "minecraft:warden",
    /** 风弹。 */
    WindChargeProjectile = "minecraft:wind_charge_projectile",
    /** 女巫。 */
    Witch = "minecraft:witch",
    /** 凋灵。 */
    Wither = "minecraft:wither",
    /** 凋灵骷髅。 */
    WitherSkeleton = "minecraft:wither_skeleton",
    /** 凋灵之首。 */
    WitherSkull = "minecraft:wither_skull",
    /** 蓝色凋灵之首。 */
    WitherSkullDangerous = "minecraft:wither_skull_dangerous",
    /** 狼。 */
    Wolf = "minecraft:wolf",
    /** 附魔之瓶。 */
    XpBottle = "minecraft:xp_bottle",
    /** 经验球。 */
    XpOrb = "minecraft:xp_orb",
    /** 僵尸疣猪兽。 */
    Zoglin = "minecraft:zoglin",
    /** 僵尸。 */
    Zombie = "minecraft:zombie",
    /** 僵尸马。 */
    ZombieHorse = "minecraft:zombie_horse",
    /** 僵尸鹦鹉螺。 */
    ZombieNautilus = "minecraft:zombie_nautilus",
    /** 僵尸猪灵。 */
    ZombiePigman = "minecraft:zombie_pigman",
    /** 僵尸村民。 */
    ZombieVillager = "minecraft:zombie_villager",
    /** 僵尸村民。 */
    ZombieVillagerV2 = "minecraft:zombie_villager_v2"
}
/**
 * Union type equivalent of the MinecraftEntityTypes enum.
 */
export type MinecraftEntityTypesUnion = keyof typeof MinecraftEntityTypes;
