/**
 * All possible MinecraftBiomeTypes
 */
export declare enum MinecraftBiomeTypes {
    /** 竹林。 */
    BambooJungle = "minecraft:bamboo_jungle",
    /** 竹林丘陵。 */
    BambooJungleHills = "minecraft:bamboo_jungle_hills",
    /** 玄武岩三角洲。 */
    BasaltDeltas = "minecraft:basalt_deltas",
    /** 沙滩。 */
    Beach = "minecraft:beach",
    /** 桦木森林。 */
    BirchForest = "minecraft:birch_forest",
    /** 桦木森林丘陵。 */
    BirchForestHills = "minecraft:birch_forest_hills",
    /** 高大桦木丘陵。 */
    BirchForestHillsMutated = "minecraft:birch_forest_hills_mutated",
    /** 原始桦木森林。 */
    BirchForestMutated = "minecraft:birch_forest_mutated",
    /** 樱花树林。 */
    CherryGrove = "minecraft:cherry_grove",
    /** 积雪沙滩。 */
    ColdBeach = "minecraft:cold_beach",
    /** 冷水海洋。 */
    ColdOcean = "minecraft:cold_ocean",
    /** 积雪针叶林。 */
    ColdTaiga = "minecraft:cold_taiga",
    /** 积雪的针叶林丘陵。 */
    ColdTaigaHills = "minecraft:cold_taiga_hills",
    /** 积雪的针叶林山地。 */
    ColdTaigaMutated = "minecraft:cold_taiga_mutated",
    /** 绯红森林。 */
    CrimsonForest = "minecraft:crimson_forest",
    /** 冷水深海。 */
    DeepColdOcean = "minecraft:deep_cold_ocean",
    /** 深暗之域。 */
    DeepDark = "minecraft:deep_dark",
    /** 冰冻深海。 */
    DeepFrozenOcean = "minecraft:deep_frozen_ocean",
    /** 温水深海。 */
    DeepLukewarmOcean = "minecraft:deep_lukewarm_ocean",
    /** 深海。 */
    DeepOcean = "minecraft:deep_ocean",
    DeepWarmOcean = "minecraft:deep_warm_ocean",
    /** 沙漠。 */
    Desert = "minecraft:desert",
    /** 沙漠丘陵。 */
    DesertHills = "minecraft:desert_hills",
    /** 沙漠湖泊。 */
    DesertMutated = "minecraft:desert_mutated",
    /** 溶洞。 */
    DripstoneCaves = "minecraft:dripstone_caves",
    /** 风袭丘陵。 */
    ExtremeHills = "minecraft:extreme_hills",
    /** 山地边缘。 */
    ExtremeHillsEdge = "minecraft:extreme_hills_edge",
    /** 风袭沙砾丘陵。 */
    ExtremeHillsMutated = "minecraft:extreme_hills_mutated",
    /** 风袭森林。 */
    ExtremeHillsPlusTrees = "minecraft:extreme_hills_plus_trees",
    /** 沙砾山地+。 */
    ExtremeHillsPlusTreesMutated = "minecraft:extreme_hills_plus_trees_mutated",
    /** 繁花森林。 */
    FlowerForest = "minecraft:flower_forest",
    /** 森林。 */
    Forest = "minecraft:forest",
    /** 繁茂的丘陵。 */
    ForestHills = "minecraft:forest_hills",
    /** 冻洋。 */
    FrozenOcean = "minecraft:frozen_ocean",
    /** 冰封山峰。 */
    FrozenPeaks = "minecraft:frozen_peaks",
    /** 冻河。 */
    FrozenRiver = "minecraft:frozen_river",
    /** 雪林。 */
    Grove = "minecraft:grove",
    /** 下界荒地。 */
    Hell = "minecraft:hell",
    /** 雪山。 */
    IceMountains = "minecraft:ice_mountains",
    /** 雪原。 */
    IcePlains = "minecraft:ice_plains",
    /** 冰刺之地。 */
    IcePlainsSpikes = "minecraft:ice_plains_spikes",
    /** 尖峭山峰。 */
    JaggedPeaks = "minecraft:jagged_peaks",
    /** 丛林。 */
    Jungle = "minecraft:jungle",
    /** 丛林边缘。 */
    JungleEdge = "minecraft:jungle_edge",
    /** 丛林边缘变种。 */
    JungleEdgeMutated = "minecraft:jungle_edge_mutated",
    /** 丛林丘陵。 */
    JungleHills = "minecraft:jungle_hills",
    /** 丛林变种。 */
    JungleMutated = "minecraft:jungle_mutated",
    /** 冻洋（旧版）。 */
    LegacyFrozenOcean = "minecraft:legacy_frozen_ocean",
    /** 温水海洋。 */
    LukewarmOcean = "minecraft:lukewarm_ocean",
    /** 繁茂洞穴。 */
    LushCaves = "minecraft:lush_caves",
    /** 红树林沼泽。 */
    MangroveSwamp = "minecraft:mangrove_swamp",
    /** 草甸。 */
    Meadow = "minecraft:meadow",
    /** 原始松木针叶林。 */
    MegaTaiga = "minecraft:mega_taiga",
    /** 巨型针叶林丘陵。 */
    MegaTaigaHills = "minecraft:mega_taiga_hills",
    /** 恶地。 */
    Mesa = "minecraft:mesa",
    /** 风蚀恶地。 */
    MesaBryce = "minecraft:mesa_bryce",
    /** 恶地高原。 */
    MesaPlateau = "minecraft:mesa_plateau",
    /** 恶地高原变种。 */
    MesaPlateauMutated = "minecraft:mesa_plateau_mutated",
    /** 繁茂的恶地高原。 */
    MesaPlateauStone = "minecraft:mesa_plateau_stone",
    /** 繁茂的恶地高原变种。 */
    MesaPlateauStoneMutated = "minecraft:mesa_plateau_stone_mutated",
    /** 蘑菇岛。 */
    MushroomIsland = "minecraft:mushroom_island",
    /** 蘑菇岛岸。 */
    MushroomIslandShore = "minecraft:mushroom_island_shore",
    /** 海洋。 */
    Ocean = "minecraft:ocean",
    /** 平原。 */
    Plains = "minecraft:plains",
    /** 巨型云杉针叶林丘陵。 */
    RedwoodTaigaHillsMutated = "minecraft:redwood_taiga_hills_mutated",
    /** 原始云杉针叶林。 */
    RedwoodTaigaMutated = "minecraft:redwood_taiga_mutated",
    /** 河流。 */
    River = "minecraft:river",
    /** 黑森林。 */
    RoofedForest = "minecraft:roofed_forest",
    /** 黑森林丘陵。 */
    RoofedForestMutated = "minecraft:roofed_forest_mutated",
    /** 热带草原。 */
    Savanna = "minecraft:savanna",
    /** 风袭热带草原。 */
    SavannaMutated = "minecraft:savanna_mutated",
    /** 热带高原。 */
    SavannaPlateau = "minecraft:savanna_plateau",
    /** 破碎的热带高原。 */
    SavannaPlateauMutated = "minecraft:savanna_plateau_mutated",
    /** 积雪山坡。 */
    SnowySlopes = "minecraft:snowy_slopes",
    /** 灵魂沙峡谷。 */
    SoulsandValley = "minecraft:soulsand_valley",
    /** 石岸。 */
    StoneBeach = "minecraft:stone_beach",
    /** 裸岩山峰。 */
    StonyPeaks = "minecraft:stony_peaks",
    /** 向日葵平原。 */
    SunflowerPlains = "minecraft:sunflower_plains",
    /** 沼泽。 */
    Swampland = "minecraft:swampland",
    /** 沼泽丘陵。 */
    SwamplandMutated = "minecraft:swampland_mutated",
    /** 针叶林。 */
    Taiga = "minecraft:taiga",
    /** 针叶林丘陵。 */
    TaigaHills = "minecraft:taiga_hills",
    /** 针叶林山地。 */
    TaigaMutated = "minecraft:taiga_mutated",
    /** 末地。 */
    TheEnd = "minecraft:the_end",
    /** 暖水海洋。 */
    WarmOcean = "minecraft:warm_ocean",
    /** 诡异森林。 */
    WarpedForest = "minecraft:warped_forest"
}
/**
 * Union type equivalent of the MinecraftBiomeTypes enum.
 */
export type MinecraftBiomeTypesUnion = keyof typeof MinecraftBiomeTypes;
